# Generated by Django 4.2.7 on 2023-11-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsr', models.CharField(max_length=10)),
                ('use_ip', models.IntegerField()),
            ],
        ),
    ]
